("https://github.com/mr-pydroid/Report-of-rubika")
("https://github.com/alirip/yftt18k-report-rubika/blob/main/Screenshot_20220920-085304_Samsung%20Internet.jpg")
("https://www.al-monitor.com/originals/2023/03/iran-death-khamenei-chants-nowruz-leader-gives-victorious-speech")
("https://news.mojahedin.org/c/زنان")
("http://www.hailsatanfilm.com")
("https://m.me11r.com")
("https://cyberpolice.gov.ir/node/168853")
("https://github.com/Tacklorix/TackLorix.git")
("https://github.com/HACKDRES2/virus-link")
("report account rubika.ir")
