("https://developers.cloudflare.com/radar/investigate/domain-ranking-datasets")
("http://data.phishtank.com/data/online-valid.json.bz2")
("http://data.phishtank.com/data/online-valid.php_serialized.bz2")
("https://www.counterextremism.com/threat/abu-sayyaf-group-asg")
("https://hole.cert.pl/domains/domains_mikrotik.rsc")
("https://liveweave.com/JUcnd7")
("https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm64.zip")
("https://github.com/mr-pydroid/Report-of-rubika")
